CREATE TABLE subjects (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          class_level INT NOT NULL
);

CREATE TABLE materials (
                           id BIGINT AUTO_INCREMENT PRIMARY KEY,
                           subject_id BIGINT NOT NULL,
                           teacher_id BIGINT NOT NULL,
                           title VARCHAR(200) NOT NULL,
                           material_type ENUM('VIDEO', 'DOCUMENT') NOT NULL,
                           file_url VARCHAR(255) NOT NULL,

    -- AI Specific Columns
                           transcript TEXT,          -- Text extracted from videos/PDFs
                           ai_summary TEXT,          -- The "Quick Review" generated by your NLP model

                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
                           FOREIGN KEY (teacher_id) REFERENCES users(id)
);